version: '3'
services:
  python2.7:
    build: ./python2.7
    image: tiangolo/uwsgi-nginx-flask:python2.7
  python2.7-alpine3.7:
    build: ./python2.7-alpine3.7
    image: tiangolo/uwsgi-nginx-flask:python2.7-alpine3.7
  python2.7-alpine3.8:
    build: ./python2.7-alpine3.8
    image: tiangolo/uwsgi-nginx-flask:python2.7-alpine3.8
  python3.5:
    build: ./python3.5
    image: tiangolo/uwsgi-nginx-flask:python3.5
  python3.6:
    build: ./python3.6
    image: tiangolo/uwsgi-nginx-flask:python3.6
  python3.6-alpine3.7:
    build: ./python3.6-alpine3.7
    image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
  python3.6-alpine3.8:
    build: ./python3.6-alpine3.8
    image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.8
  python3.7:
    build: ./python3.7
    image: tiangolo/uwsgi-nginx-flask:python3.7
  latest:
    build: ./python3.7
    image: tiangolo/uwsgi-nginx-flask:latest
  python3.7-alpine3.7:
    build: ./python3.7-alpine3.7
    image: tiangolo/uwsgi-nginx-flask:python3.7-alpine3.7
  python3.7-alpine3.8:
    build: ./python3.7-alpine3.8
    image: tiangolo/uwsgi-nginx-flask:python3.7-alpine3.8
